{"trial_id": "0063", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "c_units_1", "default": null, "conditions": [], "min_value": 4, "max_value": 128, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "c_units_2", "default": null, "conditions": [], "min_value": 4, "max_value": 128, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "d_units_1", "default": null, "conditions": [], "min_value": 4, "max_value": 128, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "d_units_2", "default": null, "conditions": [], "min_value": 4, "max_value": 128, "step": 2, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "dropout", "default": 0.4, "conditions": [], "min_value": 0.4, "max_value": 0.5, "step": null, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "lr", "default": 1e-05, "conditions": [], "min_value": 1e-05, "max_value": 0.001, "step": null, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "#_res_layers", "default": 1, "conditions": [], "values": [1, 2, 3, 4], "ordered": true}}, {"class_name": "Int", "config": {"name": "k_units", "default": null, "conditions": [], "min_value": 3, "max_value": 15, "step": 1, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "momentum", "default": 0.1, "conditions": [], "min_value": 0.1, "max_value": 0.9, "step": 0.05, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "epochs", "default": null, "conditions": [], "min_value": 10, "max_value": 200, "step": 10, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "batch_size", "default": 16, "conditions": [], "values": [16, 32, 64], "ordered": true}}], "values": {"c_units_1": 44, "c_units_2": 46, "d_units_1": 74, "d_units_2": 56, "dropout": 0.4462887806030249, "lr": 0.00022061289990916676, "#_res_layers": 4, "k_units": 14, "momentum": 0.1, "epochs": 160, "batch_size": 64}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/home/capitan/.venv/tenv/lib64/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/home/capitan/.venv/tenv/lib64/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/capitan/.venv/tenv/lib64/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/capitan/.venv/tenv/lib64/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/tmp/ipykernel_477196/3810172963.py\", line 64, in fit\n    return model.fit(\n           ^^^^^^^^^^\n  File \"/home/capitan/.venv/tenv/lib64/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/home/capitan/.venv/tenv/lib64/python3.11/site-packages/tensorflow/python/eager/execute.py\", line 59, in quick_execute\n    except TypeError as e:\ntensorflow.python.framework.errors_impl.UnknownError: Graph execution error:\n\nDetected at node StatefulPartitionedCall defined at (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n\n  File \"<frozen runpy>\", line 88, in _run_code\n\n  File \"/home/capitan/.venv/tenv/lib64/python3.11/site-packages/ipykernel_launcher.py\", line 18, in <module>\n\n  File \"/home/capitan/.venv/tenv/lib64/python3.11/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n\n  File \"/home/capitan/.venv/tenv/lib64/python3.11/site-packages/ipykernel/kernelapp.py\", line 739, in start\n\n  File \"/home/capitan/.venv/tenv/lib64/python3.11/site-packages/tornado/platform/asyncio.py\", line 205, in start\n\n  File \"/usr/lib64/python3.11/asyncio/base_events.py\", line 608, in run_forever\n\n  File \"/usr/lib64/python3.11/asyncio/base_events.py\", line 1936, in _run_once\n\n  File \"/usr/lib64/python3.11/asyncio/events.py\", line 84, in _run\n\n  File \"/home/capitan/.venv/tenv/lib64/python3.11/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n\n  File \"/home/capitan/.venv/tenv/lib64/python3.11/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n\n  File \"/home/capitan/.venv/tenv/lib64/python3.11/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n\n  File \"/home/capitan/.venv/tenv/lib64/python3.11/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n\n  File \"/home/capitan/.venv/tenv/lib64/python3.11/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n\n  File \"/home/capitan/.venv/tenv/lib64/python3.11/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n\n  File \"/home/capitan/.venv/tenv/lib64/python3.11/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n\n  File \"/home/capitan/.venv/tenv/lib64/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3047, in run_cell\n\n  File \"/home/capitan/.venv/tenv/lib64/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3102, in _run_cell\n\n  File \"/home/capitan/.venv/tenv/lib64/python3.11/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n\n  File \"/home/capitan/.venv/tenv/lib64/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3306, in run_cell_async\n\n  File \"/home/capitan/.venv/tenv/lib64/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3489, in run_ast_nodes\n\n  File \"/home/capitan/.venv/tenv/lib64/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3549, in run_code\n\n  File \"/tmp/ipykernel_477196/874603744.py\", line 5, in <module>\n\n  File \"/home/capitan/.venv/tenv/lib64/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 234, in search\n\n  File \"/home/capitan/.venv/tenv/lib64/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n\n  File \"/home/capitan/.venv/tenv/lib64/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n\n  File \"/home/capitan/.venv/tenv/lib64/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n\n  File \"/home/capitan/.venv/tenv/lib64/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n\n  File \"/tmp/ipykernel_477196/3810172963.py\", line 64, in fit\n\n  File \"/home/capitan/.venv/tenv/lib64/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/home/capitan/.venv/tenv/lib64/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 371, in fit\n\n  File \"/home/capitan/.venv/tenv/lib64/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 219, in function\n\n  File \"/home/capitan/.venv/tenv/lib64/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 132, in multi_step_on_iterator\n\nFailed to determine best cudnn convolution algorithm for:\n%cudnn-conv-bw-filter.21 = (f32[46,44,1,14]{3,2,1,0}, u8[0]{0}) custom-call(f32[54,44,1,60]{3,2,1,0} %bitcast.20270, f32[54,46,1,59]{3,2,1,0} %bitcast.20272), window={size=1x14 pad=0_0x6_6}, dim_labels=bf01_oi01->bf01, custom_call_target=\"__cudnn$convBackwardFilter\", metadata={op_type=\"Conv2DBackpropFilter\" op_name=\"gradient_tape/functional_1/conv1d_11_1/convolution/Conv2DBackpropFilter\" source_file=\"/home/capitan/.venv/tenv/lib64/python3.11/site-packages/tensorflow/python/framework/ops.py\" source_line=1200}, backend_config={\"operation_queue_id\":\"0\",\"wait_on_operation_queues\":[],\"cudnn_conv_backend_config\":{\"conv_result_scale\":1,\"activation_mode\":\"kNone\",\"side_input_scale\":0,\"leakyrelu_alpha\":0},\"force_earliest_schedule\":false}\n\nOriginal error: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 16890560 bytes. [tf-allocator-allocation-error='']\n\nTo ignore this failure and try to use a fallback algorithm (which may have suboptimal performance), use XLA_FLAGS=--xla_gpu_strict_conv_algorithm_picker=false.  Please also file a bug for the root cause of failing autotuning.\n\t [[{{node StatefulPartitionedCall}}]] [Op:__inference_multi_step_on_iterator_5423309]\n"}